#OpenWeatherMap
openweather.api.key={KEY}
openweather.api.url=https://api.openweathermap.org/data/2.5/
#MongoDB
spring.data.mongodb.uri=mongodb://app_user:app_password@localhost:27017/weather_db?authSource=weather_db
